site_name: Codefresh
repo_url: https://github.com/codefresh-io/cli-v2
strict: true
theme:
  name: material
  palette:
    primary: teal
  font:
    text: 'Work Sans'
  logo: 'assets/logo.png'
  favicon: 'assets/favicon.png'
  custom_dir: 'overrides'
extra_javascript:
- assets/versions.js
extra_css:
- assets/versions.css
markdown_extensions:
- codehilite
- admonition
- toc:
    permalink: true
nav:
  - Introduction: index.md
  - Releases ⧉: https://github.com/codefresh-io/cli-v2/releases
  - Issues ⧉: https://github.com/codefresh-io/cli-v2/issues
  - Slack ⧉: https://cloud-native.slack.com/archives/C0207C47D0X
